### ISSUE TITLE
just retrieve a lat long from TLE

### ISSUE THREAD

**Issue by eqcq** [shupp/Predict#1]
Hi there and thanks for your work.
I would like to retrieve the actual position (lat,long,alt) of a satellite using it tle

is there an easy way to achieve this with your library ?

thx

**Comment by shupp** [comment]
Yes.  See this gist for an example with the ISS:

https://gist.github.com/shupp/1741086

Cheers,

Bill

**Comment by eqcq** [comment]
thanks a lot it's helpfull !
