### ISSUE TITLE
Use future time stamp for TLE epoch date

### ISSUE THREAD

**Issue by gaiterjones** [shupp/Predict#2]
Firstly, many thanks for your work on this, it's been a number of years since you developed it but it's still working well with PHP 7.4 today!

As I understand it the orbit data is derived from the epoch timestamp in the TLE, if I want to run a prediction for orbit data for the next X hours how can I pass in a custom epoch timestamp?

**Comment by shupp** [comment]
@gaiterjones I'm glad to hear you find this useful!

The TLE actually just represents the time of the observation of that object.  So the idea is that, for precision, always use an observation (TLE) as close to the time of prediction you can.  For example, if you want to look up an ISS position from two months ago, using a TLE that was recorded yesterday will not be as accurate as a TLE recorded two months ago.

The Predict library takes in timestamps in its function so you can indicate when you want to run your prediction for.  In the case of looking up visible passes, you can see that on line [41 of the example](https://github.com/shupp/Predict/blob/master/examples/visible_passes.php#L41), the current daynum is derived from the current timestamp.  You could also use a different timestamp, and convert it with [unix2daynum](https://github.com/shupp/Predict/blob/master/Predict/Time.php#L149), and pass that in instead.

As far as changing the amount of time to look forward, you can use the `$maxdt` argument to [get_passes](https://github.com/shupp/Predict/blob/master/Predict.php#L744).  Though it appears that expects to be an integer of days, you could try a float for a partial day, not sure if that'll work or not.

Hope that helps,

Bill

**Comment by gaiterjones** [comment]
thanks for the quick reply, I didn't look properly at get_pass() so I will give it another go and let you know!

**Comment by gaiterjones** [comment]
For anyone else trying to do the same thing the way to achieve this is to create a new predict calc function in Predict.php.

Here is what I am using, I can pass in any correctly formatted timestamp ($t) with the $sat object to get the orbit data prediction I want.


```
    /** SGP4SDP4 driver for doing AOS/LOS calculations.
     *  @param Predict_Sat $sat The satellite data.
     *  @param Predict_QTH $qth The QTH observer location data.
     *  @param float       $t   The time for calculation (Julian Date)
     *
     */
    public function predict_gaiterjones(Predict_Sat $sat, $t)
    {
        $obs_set      = new Predict_ObsSet();
        $sat_geodetic = new Predict_Geodetic();
        $obs_geodetic = new Predict_Geodetic();

        $obs_geodetic->lon = 0.0;
        $obs_geodetic->lat = 0.0;
        $obs_geodetic->alt = 0.0;
        $obs_geodetic->theta = 0;

        $sat->jul_utc = $t;
        $sat->tsince = ($sat->jul_utc - $sat->jul_epoch) * self::xmnpda;

        /* call the norad routines according to the deep-space flag */
        $sgpsdp = Predict_SGPSDP::getInstance($sat);
        if ($sat->flags & Predict_SGPSDP::DEEP_SPACE_EPHEM_FLAG) {
            $sgpsdp->SDP4($sat, $sat->tsince);
        } else {
            $sgpsdp->SGP4($sat, $sat->tsince);
        }

        Predict_Math::Convert_Sat_State($sat->pos, $sat->vel);

        /* get the velocity of the satellite */
        $sat->vel->w = sqrt($sat->vel->x * $sat->vel->x + $sat->vel->y * $sat->vel->y + $sat->vel->z * $sat->vel->z);
        $sat->velo = $sat->vel->w;
        Predict_SGPObs::Calculate_Obs($sat->jul_utc, $sat->pos, $sat->vel, $obs_geodetic, $obs_set);
        Predict_SGPObs::Calculate_LatLonAlt($sat->jul_utc, $sat->pos, $sat_geodetic);

        while ($sat_geodetic->lon < -self::pi) {
            $sat_geodetic->lon += self::twopi;
        }

        while ($sat_geodetic->lon > (self::pi)) {
            $sat_geodetic->lon -= self::twopi;
        }

        $sat->az = Predict_Math::Degrees($obs_set->az);
        $sat->el = Predict_Math::Degrees($obs_set->el);
        $sat->range = $obs_set->range;
        $sat->range_rate = $obs_set->range_rate;
        $sat->ssplat = Predict_Math::Degrees($sat_geodetic->lat);
        $sat->ssplon = Predict_Math::Degrees($sat_geodetic->lon);
        $sat->alt = $sat_geodetic->alt;
        $sat->ma = Predict_Math::Degrees($sat->phase);
        $sat->ma *= 256.0 / 360.0;
        $sat->phase = Predict_Math::Degrees($sat->phase);

        /* same formulas, but the one from predict is nicer */
        //sat->footprint = 2.0 * xkmper * acos (xkmper/sat->pos.w);
        $sat->footprint = 12756.33 * acos(self::xkmper / (self::xkmper + $sat->alt));
        $age = $sat->jul_utc - $sat->jul_epoch;
        $sat->orbit = floor(($sat->tle->xno * self::xmnpda / self::twopi +
                        $age * $sat->tle->bstar * self::ae) * $age +
                        $sat->tle->xmo / self::twopi) + $sat->tle->revnum - 1;

        return $sat;
    }
```
