### ISSUE TITLE
Generate the polar view

### ISSUE THREAD

**Issue by BaptisteBuvron** [shupp/Predict#4]
Hi,
First of all thank you for your work, it is very useful to me.

I was wondering what tools did you use to generate this polar view?  :
![](https://camo.githubusercontent.com/a11d6b373a57852097421bf538a2852080825e151c9043e598a2c33c9440d611/68747470733a2f2f7261772e6769746875622e636f6d2f73687570702f507265646963742f6d61737465722f6578616d706c65732f706173735f706f6c61725f706c6f742e706e67)

Regards,

Baptiste

**Comment by shupp** [comment]
Hi @BaptisteBuvron, I'm glad you find the work useful.

This polar view was drawn manually using [PHP's ImageMagick bindings](https://www.php.net/manual/en/book.imagick.php).  That code is not available as an example, though.

Cheers,

Bill
